### ISSUE TITLE
Peer-peer code review: Suggested Changes to the Project

### ISSUE THREAD

**Issue by MarcoAurelioAntonio** [OmarMWarraich/Portfolio#15]
I would like to recommend that you complete the readme file with a more detailed description of what the project is about so that each person who visits it knows what it is about.

**Comment by SimonGideon** [comment]
### Suggest the changes to your Portfolio
1. I suggest you change the color of the message icon in the nav bar section to fit the UI of the project.
2. I think it will be better if you'll change the padding of the input fields in the contact form section to math the UI design of the the project.

**Comment by OmarMWarraich** [comment]
Consider it done.
