### ISSUE TITLE
Solve Linter Errors in you code.

### ISSUE THREAD

**Issue by SimonGideon** [OmarMWarraich/Portfolio#5]
**Linter Errors**
![image](https://user-images.githubusercontent.com/61404403/178518492-2ad8d2c3-01c2-40e2-bb80-c32cba561256.png)

Lenters are very vital in the following ways: 

1. Catching syntax errors is more efficient. There is no need to debug simple mistakes like typos - the linter does it for you.
2. The entire codebase looks like it was written by one person.
3. Programmers can focus on solving problems instead of cleaning up the code.

@OmarMWarraich

**Comment by OmarMWarraich** [comment]
Ok. @SimonGideon.
